"""add_watermark.py — burn the AWAKEDEN wordmark into finished videos ($0 ffmpeg).

Positions (user-locked 2026-07-21, from the father_forgive_them samples):
  9:16 (shorts)     top-LEFT   — the one top spot clear of TikTok/Shorts UI icons
                                 besides center; user picked left by eye.
  16:9 (long films) top-RIGHT  — classic broadcast bug, YouTube draws nothing there.

Overlay asset: _brand/awakeden_watermark_overlay.png (transparent, soft shadow;
regenerated by pipeline/thumbnails.py brand_assets — AWAK bone + EDEN red).

Safe + idempotent:
  - the untouched original is kept beside the final as <stem>.prewm.bak.mp4
    (".bak." names are skipped by pipeline/finality.py and the scorers)
  - a file whose backup already exists is skipped (already watermarked)
  - the new encode must match the original duration within 0.05s or it is
    discarded and the original left in place (fail-closed)

  .venv\\Scripts\\python.exe add_watermark.py            # the 22 shipped finals
  .venv\\Scripts\\python.exe add_watermark.py <video>...  # specific file(s)
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
WM = ROOT / "_brand" / "awakeden_watermark_overlay.png"

LONG_FINALS = [
    ROOT / "longform/01_Isaiah_53_Suffering_Servant/v1/visual_16x9_inked/LivingPage_Isaiah53_16x9_scored_sfx.mp4",
    ROOT / "longform/02_Psalm_22_Song_From_The_Cross/v1/visual_16x9_inked/LivingPage_Psalm22_16x9_scored_sfx.mp4",
    ROOT / "longform/04_The_Bronze_Serpent/v1/visual_16x9_inked/BronzeSerpent_16x9_scored_sfx.mp4",
]


def shipped_finals() -> list[Path]:
    vids = []
    for cluster in ("cluster_01_cross", "cluster_02_resurrection"):
        for piece in sorted((ROOT / "batches" / cluster).iterdir()):
            f = piece / "visual" / f"{piece.name}_sfx.mp4"
            if f.is_file():
                vids.append(f)
    return vids + [f for f in LONG_FINALS if f.is_file()]


def probe(p: Path) -> tuple[int, int, float]:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0",
         "-show_entries", "stream=width,height", "-show_entries", "format=duration",
         "-of", "json", str(p)], capture_output=True, text=True, check=True).stdout
    j = json.loads(out)
    st = j["streams"][0]
    return int(st["width"]), int(st["height"]), float(j["format"]["duration"])


def watermark(video: Path) -> str:
    bak = video.with_name(video.stem + ".prewm.bak.mp4")
    if bak.exists():
        return "skip (already watermarked)"
    w, h, dur = probe(video)
    if h > w:      # portrait short: top-left (40,70 on a 1080x1920 page)
        wm_w = round(w * 200 / 1080)
        x, y = round(w * 40 / 1080), round(h * 70 / 1920)
    else:          # landscape film: top-right (28px margins on 1920x1080)
        wm_w = round(w * 260 / 1920)
        x, y = w - wm_w - round(w * 28 / 1920), round(h * 28 / 1080)
    tmp = video.with_name(video.stem + ".wm.tmp.mp4")
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-i", str(video), "-i", str(WM),
         "-filter_complex", f"[1]scale={wm_w}:-1[wm];[0][wm]overlay={x}:{y}",
         "-c:v", "libx264", "-crf", "18", "-preset", "medium",
         "-c:a", "copy", "-movflags", "+faststart", str(tmp)], check=True)
    _, _, dur2 = probe(tmp)
    if abs(dur2 - dur) > 0.05:
        tmp.unlink()
        return f"FAIL duration drift {dur:.2f}->{dur2:.2f}s (original untouched)"
    video.rename(bak)
    tmp.rename(video)
    return f"OK ({w}x{h}, wm {wm_w}px at {x},{y})"


def main() -> int:
    targets = [Path(a).resolve() for a in sys.argv[1:]] or shipped_finals()
    if not WM.is_file():
        sys.exit(f"missing overlay asset: {WM} (run pipeline/thumbnails.py)")
    fails = 0
    for v in targets:
        r = watermark(v)
        print(f"  {r:<44} {v.relative_to(ROOT)}", flush=True)
        fails += r.startswith("FAIL")
    print(f"done: {len(targets)} file(s), {fails} FAIL")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
