#!/usr/bin/env python
"""One-off: append the 36 v3 grounded still specs (distinct-per-beat upgrade, LIVINGPAGE_STANDARD 3b)."""
import json
from pathlib import Path

p = Path(__file__).resolve().parent / "still_specs.json"
d = json.loads(p.read_text(encoding="utf-8"))
S = d["specs"]

NEW = {
 "golgotha_three_crosses_ridge": dict(beat=26, verse="the witness statement from a cross (Ps 22 read forensically)", shot="GROUND_LEVEL", signature="crosses:ridge-silhouette-trio", arms="n/a",
   prompt="a GROUND-LEVEL view across dark scrubland to a low ridge where three crosses stand small and stark against a vast bruised storm sky, one shaft of cold light striking the middle cross; epic emptiness; 1st-century",
   distinct_from="storm_over_jerusalem (city+temple wide) and cross_hill_pullback (single cross) - this is THREE crosses tiny on a ridge"),
 "ninth_hour_darkness": dict(beat=2, verse="Matthew 27:45 - darkness over the land at the ninth hour", shot="WIDE_ESTABLISH", signature="sky:darkened-sun-city", arms="n/a",
   prompt="a WIDE view over flat-roofed 1st-century Jerusalem rooftops as an unnatural darkness swallows the midday sun, a dim ring of light in a black-green sky, birds scattering; dread; 1st-century",
   distinct_from="storm_over_jerusalem (temple + crosses) - this is the DARKENED SUN over rooftops, no cross"),
 "roman_nails_pouch": dict(beat=1, verse="the crucifixion nails (Ps 22:16)", shot="MACRO_DETAIL", signature="nails:pouch-spill", arms="a soldier's hand tipping the pouch",
   prompt="a MACRO of a worn leather pouch tipped by a soldier's rough hand, long slender iron nails with small square heads spilling out across a flat stone in hard light; plain thin spikes; 1st-century",
   distinct_from="pierced_hands_feet (a nail IN a hand) - these are loose nails spilling from a pouch"),
 "david_scroll_sealed": dict(beat=12, verse="David wrote this song (Ps 22 title)", shot="MACRO_DETAIL", signature="scroll:sealed-signet", arms="one ringed hand pressing a clay seal",
   prompt="a MACRO of an aged royal hand with a signet ring pressing a small clay seal onto the tie of a freshly rolled papyrus scroll by lamplight, the papyrus surface only soft indistinct texture; 1st-millennium-BC",
   distinct_from="two_scrolls_compared (two open scrolls) - this is ONE rolled scroll being SEALED"),
 "jerusalem_night_lyre": dict(beat=13, verse="David composing under the night sky", shot="WIDE_ESTABLISH", signature="david:rooftop-distant-night", arms="n/a",
   prompt="a WIDE moonlit view of ancient stone rooftops and a city wall, one small distant figure seated on a high rooftop corner with a lyre against the starfield; lonely and quiet; 1st-millennium-BC",
   distinct_from="david_psalmist (close, face visible) - this is a tiny DISTANT figure in a wide night city"),
 "execution_stakes_field": dict(beat=15, verse="a public execution (the death David describes)", shot="WIDE_ESTABLISH", signature="execution:empty-stakes-field", arms="n/a",
   prompt="a WIDE bleak view of a rocky execution ground outside a city wall, several empty upright wooden stakes and crossbeams against a grey sky, dark birds circling far off; dread, no figures; 1st-century",
   distinct_from="golgotha_three_crosses_ridge (three crosses on a ridge) - this is an EMPTY execution ground of bare stakes"),
 "mockers_below_cross_low": dict(beat=20, verse="Psalm 22:8 - the mockers' taunt hurled up at the cross", shot="OVER_SHOULDER", signature="mockers:shoulders-up-at-cross", arms="one mocker's arm flung up in derision",
   prompt="an OVER-THE-SHOULDER view from behind two jeering men in 1st-century robes, one arm flung up in derision, looking steeply UP toward the crucified figure high on the cross against the dark sky above them; hostile energy below, stillness above; 1st-century",
   distinct_from="mockers_wag_heads (frontal faces w/ Christ small centre) - this is from BEHIND the mockers looking UP"),
 "spit_shout_macro": dict(beat=16, verse="Psalm 22:7 - they shoot out the lip (the jeer itself)", shot="CLOSE_PORTRAIT", signature="mocker:single-jeer-profile", arms="n/a",
   prompt="a hard CLOSE profile of one 1st-century man mid-jeer, lip curled and teeth bared, spittle flecks catching the light against a dark blurred crowd; ugly contempt; 1st-century",
   distinct_from="mocker_faces_trio (three faces frontal) - this is ONE jeering profile, extreme close"),
 "old_king_hands_rings": dict(beat=21, verse="a king who died of old age (contrast with the psalm's death)", shot="MACRO_DETAIL", signature="david:aged-hands-rings", arms="two aged hands at rest on a woven blanket",
   prompt="a MACRO of two aged royal hands at rest on a woven blanket, gold rings loose on thin fingers, warm lamplight, utterly peaceful; a safe death; 1st-millennium-BC",
   distinct_from="david_old_deathbed (the wide deathbed scene) - this is only the resting HANDS"),
 "shepherd_boy_sling": dict(beat=22, verse="David the soldier-king's real life (never executed)", shot="FULL_FIGURE", signature="david:young-shepherd-sling", arms="one hand swinging a leather sling at his side",
   prompt="a FULL-FIGURE view of a young shepherd on a green hillside among sheep, a leather sling swinging loose from one hand, morning light; vigorous life; 1st-millennium-BC",
   distinct_from="david_psalmist (the aged singer) - this is YOUNG David the shepherd"),
 "war_helmet_spear_rest": dict(beat=22, verse="a soldier and a king (his battles ended in peace)", shot="MACRO_DETAIL", signature="soldier:arms-at-rest", arms="n/a",
   prompt="a MACRO of an old dented bronze helmet and a tall spear leaned together against a stone wall by a bed, dust motes in a warm shaft of light; wars long over; 1st-millennium-BC",
   distinct_from="old_king_hands_rings (hands on blanket) - this is the retired WEAPONS by the wall"),
 "wrists_bound_beam_macro": dict(beat=34, verse="a man fixed to wood through his hands (Ps 22:16)", shot="MACRO_DETAIL", signature="wound:wrist-lashed-beam", arms="one wrist lashed and nailed to the rough beam, tendons taut",
   prompt="a MACRO of a single forearm and wrist lashed with cord and nailed to a rough wooden beam, the tendons taut under the skin, a thin dark line of blood in the wood grain, storm light; no face; 1st-century",
   distinct_from="pierced_hands_feet (open palm with nail) - this is the LASHED WRIST from the side, tendons straining"),
 "ribs_stretched_macro": dict(beat=28, verse="Psalm 22:14 - all my bones are out of joint", shot="CLOSE_PORTRAIT", signature="body:ribcage-strain", arms="n/a (torso only)",
   prompt="a CLOSE side-lit view of a gaunt stretched ribcage under taut skin, the torso of a man hanging with arms high out of frame, each rib ridged in hard chiaroscuro light; reverent, no face; 1st-century",
   distinct_from="poured_out_bones (full low-angle figure) - this is ONLY the strained ribcage, side view"),
 "clay_potsherd_dust": dict(beat=29, verse="Psalm 22:15 - my strength is dried up like a potsherd", shot="MACRO_DETAIL", signature="thirst:potsherd", arms="n/a",
   prompt="a MACRO of a single cracked shard of dry clay pottery lying in pale dust, hairline cracks spreading, heat shimmer; utter dryness; 1st-century",
   distinct_from="thirst_dust (the parched face) - this is the psalm's POTSHERD image itself, no figure"),
 "water_spilled_stone": dict(beat=48, verse="Psalm 22:14 - I am poured out like water", shot="MACRO_DETAIL", signature="poured:water-on-stone", arms="n/a",
   prompt="a MACRO of clear water spilling from a tipped clay jar across worn flagstones, the thin sheet of water catching one line of light as it runs away into the cracks; loss; 1st-century",
   distinct_from="poured_out_bones (the crucified figure) - this is the WATER image literal: a jar poured out"),
 "sponge_vinegar_jar": dict(beat=30, verse="John 19:29 - a vessel full of vinegar", shot="MACRO_DETAIL", signature="vinegar:jar-and-sponge", arms="n/a",
   prompt="a MACRO of a squat clay jar of dark vinegar with a rough dry sponge and a long reed lying beside it on stony ground, hard afternoon light; waiting; 1st-century",
   distinct_from="vinegar_sponge (the sponge lifted on the reed) - this is the jar and sponge on the GROUND, before"),
 "dice_cup_shadow": dict(beat=37, verse="Psalm 22:18 - they cast lots", shot="MACRO_DETAIL", signature="lots:cup-tipping", arms="one soldier's hand tipping the horn cup",
   prompt="a MACRO of a soldier's hand tipping a horn dice-cup, small carved knucklebones caught mid-fall above the stone, long hard shadows; the moment before they land; 1st-century",
   distinct_from="lots_dice_closeup (bones already cast on the robe) - this is the CUP TIPPING, bones mid-air"),
 "vesture_seamless_folded": dict(beat=64, verse="John 19:23-24 - the coat without seam", shot="MACRO_DETAIL", signature="vesture:folded-topdown", arms="n/a",
   prompt="a MACRO top-down of a single seamless woven robe folded in a neat square on stony ground, one small carved knucklebone resting on it, dust in the light; the prize of the lot; 1st-century",
   distinct_from="garment_tug (fists pulling the robe) - this is the robe FOLDED and still, top-down"),
 "john_at_cross_foot": dict(beat=38, verse="John 19:35 - he that saw it bare record", shot="FULL_FIGURE", signature="witness:john-at-foot", arms="both hands clutched to his chest as he looks up",
   prompt="a FULL-FIGURE view of a young 1st-century disciple standing at the foot of the towering cross, wind pulling at his cloak, both hands clutched to his chest as he looks steeply up, the cross base and lower beam framing him; the witness; 1st-century",
   distinct_from="kneeling_at_cross (tiny kneelers at the base) - this is ONE standing young witness, mid shot"),
 "scholars_debate_two": dict(beat=46, verse="a genuine scholarly dispute, honestly raised", shot="INTERIOR_SCENE", signature="scholarship:two-in-dispute", arms="one scholar's hand raised mid-point, the other's palm open on the table",
   prompt="an INTERIOR view of two Near-Eastern scholars facing each other across a lamplit table stacked with rolled scrolls, one hand raised mid-argument, the other open in honest concession, warm flame light and deep shadow; respectful dispute; antiquity",
   distinct_from="greek_ot_scroll (a row of translators) and scholar_hand_on_text (one scholar alone) - this is TWO scholars in face-to-face dispute"),
 "quill_ink_drop": dict(beat=35, verse="yet there it is, in ink, centuries early", shot="MACRO_DETAIL", signature="ink:reed-pen-drop", arms="one hand lifting the reed pen",
   prompt="a MACRO of a hand lifting a reed pen from a small clay inkwell, one dark drop of ink falling back, lamplight glinting on the wet nib; the act of writing; antiquity",
   distinct_from="disputed_word_marks (marks on parchment) - this is the PEN and the ink drop, no writing visible"),
 "hebrew_scroll_edge_light": dict(beat=44, verse="the traditional Hebrew text (the disputed reading)", shot="MACRO_DETAIL", signature="scroll:edge-curl", arms="n/a",
   prompt="a MACRO of the curling edge of an ancient darkened scroll lifting slightly in lamplight, the surface only soft indistinct texture, fibres and cracks catching the flame glow; age itself; antiquity",
   distinct_from="disputed_word_marks (a spread with marks) - this is only the curling EDGE of one ancient scroll"),
 "lion_shadow_wall": dict(beat=45, verse="Psalm 22:13 - as a ravening and a roaring lion", shot="SILHOUETTE", signature="lion:shadow-on-wall", arms="n/a",
   prompt="the huge SHADOW of a prowling lion cast across a torchlit mud-brick wall at night, the beast itself unseen, torch flame guttering low in the corner; menace implied; 1st-millennium-BC",
   distinct_from="lion_gape (the roaring head itself) - this is only the SHADOW on a wall"),
 "alexandria_harbor_night": dict(beat=52, verse="the Septuagint translated in Alexandria, two centuries before", shot="WIDE_ESTABLISH", signature="city:alexandria-harbor", arms="n/a",
   prompt="a WIDE dusk view of an ancient Mediterranean harbor city, moored ships and colonnaded quays, a great lighthouse tower with its fire burning against the last light; Hellenistic Egypt; antiquity",
   distinct_from="storm_over_jerusalem (Jerusalem + temple) - this is the Greek HARBOR city with the lighthouse"),
 "seventy_scribes_lamps": dict(beat=52, verse="translated by Jewish scholars (the Seventy)", shot="INTERIOR_SCENE", signature="scholarship:rows-of-scribes", arms="n/a",
   prompt="an INTERIOR wide of a long Hellenistic hall where rows of Jewish scribes work at low tables, each under his own small oil lamp, dozens of warm points of light in the gloom, scroll surfaces only soft texture; the great translation; antiquity",
   distinct_from="greek_ot_scroll (a knot of scholars at one table) - this is ROWS of many scribes under many lamps"),
 "roads_converge_valley": dict(beat=51, verse="one disputed word does not carry it; the convergence does", shot="HIGH_CRANE", signature="symbol:roads-to-one-point", arms="n/a",
   prompt="a HIGH view of five pale footpaths descending different dark hillsides and meeting at a single sunlit crossing point on the valley floor; the lines converge on one place; timeless ancient land",
   distinct_from="nations_streaming_wide (crowded roads to a hill of light) - these are EMPTY paths converging in a valley"),
 "cry_profile_dark": dict(beat=61, verse="Matthew 27:46 - Jesus cried with a loud voice", shot="SILHOUETTE", signature="christ-cry:profile-rim-light", arms="n/a (head and shoulders only)",
   prompt="a stark SILHOUETTE profile of the crucified Christ's head thrown back mid-cry against a black sky, one hard rim of cold light tracing the brow, open mouth and beard, all else darkness; the cry itself; 1st-century",
   distinct_from="cry_ninth_hour (lit full figure) and face_anguish_closeup (lit frontal face) - this is a black rim-lit PROFILE"),
 "synagogue_listeners_lean": dict(beat=58, verse="how a first-century Jew heard a psalm quoted", shot="INTERIOR_SCENE", signature="listeners:leaning-in", arms="n/a",
   prompt="an INTERIOR of a small stone synagogue where seated listeners lean forward into the lamplight toward an unseen reader, rapt weathered faces half-lit, deep warm shadow behind; the pull of the word; 1st-century",
   distinct_from="first_century_reader (the reader himself) - this is the LISTENERS leaning toward him"),
 "hill_crowd_watching_storm": dict(beat=65, verse="out loud, in front of witnesses", shot="WIDE_MULTITUDE", signature="witnesses:dark-ring-storm", arms="n/a",
   prompt="a WIDE view of a dark ring of onlookers gathered on a slope beneath a swirling storm sky, all faces turned toward a distant lit rise where a cross stands small, dust blowing through; the watching crowd; 1st-century",
   distinct_from="mockers_wag_heads (close mocking pair) and kneeling_at_cross (kneelers at base) - this is a wide DARK RING of witnesses under storm"),
 "tear_track_macro": dict(beat=66, verse="this one is about me (the personal claim)", shot="MACRO_DETAIL", signature="face:single-eye-tear", arms="n/a",
   prompt="an EXTREME MACRO of a single human eye, lash-shadowed, one tear cutting a clean track through dust on the skin, a tiny reflection of a cross in the wet of the eye; intimate; 1st-century",
   distinct_from="cry_face_tears (whole face) - this is ONE EYE ONLY with the cross reflected in it"),
 "substitute_shadow": dict(beat=90, verse="he bore the forsaking in our place (substitution)", shot="HIGH_CRANE", signature="substitution:shadow-over-people", arms="n/a",
   prompt="a HIGH view at dawn of a small huddled group of ordinary people on pale ground, the long dark shadow of an unseen cross falling across the ground BESIDE them, leaving them standing in clean light; it fell on him, not them; 1st-century",
   distinct_from="kneeling_at_cross (kneeling AT the cross) - here the cross is unseen and its SHADOW spares the people"),
 "grave_clothes_folded_macro": dict(beat=78, verse="John 20:7 - the linen clothes lying folded", shot="MACRO_DETAIL", signature="resurrection:folded-linen", arms="n/a",
   prompt="a MACRO of the white linen grave-cloths lying neatly folded on the cut stone ledge, a shaft of pale dawn light across the weave, dust motes rising; absence as victory; 1st-century",
   distinct_from="empty_tomb_open (the whole tomb interior) - this is only the FOLDED LINEN close up"),
 "stone_rolled_groove": dict(beat=73, verse="the stone rolled away (the grave could not hold him)", shot="MACRO_DETAIL", signature="resurrection:stone-in-groove", arms="n/a",
   prompt="a MACRO along the carved stone groove of a tomb entrance, the great round sealing stone rolled fully OPEN at the groove's end, morning light flooding through the gap it left; the open way; 1st-century",
   distinct_from="empty_tomb_open (interior with ledge) - this is the ROLLED STONE in its groove from outside"),
 "congregation_hands_lifted": dict(beat=74, verse="in the midst of the congregation will I praise thee (Ps 22:22)", shot="WIDE_MULTITUDE", signature="congregation:hands-lifted-rear", arms="many hands lifted high toward the light",
   prompt="a WIDE view from BEHIND a packed congregation of 1st-century worshippers, dozens of hands lifted high toward a warm light source ahead, robes and prayer shawls edge-lit; corporate praise; 1st-century",
   distinct_from="kindreds_bowing (a bowing ring seen frontally) - this is from BEHIND, hands LIFTED not bowed"),
 "morning_birds_hill": dict(beat=83, verse="the hinge from night to morning", shot="WIDE_ESTABLISH", signature="dawn:birds-rising", arms="n/a",
   prompt="a WIDE view of birds rising in a loose spiral off a rocky hilltop into first light, the empty cross small at the crest, long soft dawn shadows down the slope; release; 1st-century",
   distinct_from="dawn_empty_cross (static dawn wide) - this one is defined by the RISING BIRDS"),
 "threshold_open_door": dict(beat=96, verse="the congregation it ends in still has room for you (the invitation)", shot="GROUND_LEVEL", signature="invitation:open-door-light", arms="n/a",
   prompt="a GROUND-LEVEL view up a worn stone path to an ancient open doorway at dusk, warm firelight and moving shadows of a gathering spilling out across the threshold toward the viewer, the door standing wide; room inside; 1st-century",
   distinct_from="hand_reaching_closeup (the scarred hand) - this is the OPEN DOOR with light spilling out"),
}
for k, v in NEW.items():
    S[k] = v
p.write_text(json.dumps(d, indent=2, ensure_ascii=False), encoding="utf-8")
print("added", len(NEW), "specs; total", len(S))
