"""Assembly-stage handoff: write edit_plan.json + reviews + timeline + audit +
upstream_notes, and a browser index.html that plays the cut and the reel next
to the per-slot jigsaw (which clip sits under which words).
"""
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from pipeline.assembly_models import (
    AssemblyAudit,
    ClipAsset,
    EditPlan,
    EditPlanReview,
    NarrationSegment,
)
from pipeline.assembly_render import REEL_NAME, VIRAL_CUT_NAME


ASSEMBLY_SUBDIR = "assembly"


def assembly_dir(v1_folder: Path) -> Path:
    return v1_folder / ASSEMBLY_SUBDIR


def _review_dict(r: EditPlanReview | None) -> dict | None:
    if r is None:
        return None
    return {
        "overall": r.overall,
        "panel": [asdict(a) for a in r.panel],
        "gates": [asdict(g) for g in r.gates],
        "priority_fixes": r.priority_fixes,
    }


def write_assembly_artifacts(
    v1_folder: Path,
    segments: list[NarrationSegment],
    clips: list[ClipAsset],
    plan: EditPlan,
    self_review: EditPlanReview,
    independent_review: EditPlanReview | None,
    audit: AssemblyAudit | None,
) -> Path:
    out = assembly_dir(v1_folder)
    out.mkdir(parents=True, exist_ok=True)
    clips_by_index = {c.scene_index: c for c in clips}

    doc = {
        "plan": asdict(plan),
        "self_review": _review_dict(self_review),
        "independent_review": _review_dict(independent_review),
        "audit": asdict(audit) if audit else None,
        "authoritative_overall": (
            independent_review.overall if independent_review else self_review.overall
        ),
    }
    (out / "edit_plan.json").write_text(
        json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")

    (out / "timeline.json").write_text(
        json.dumps([asdict(s) for s in segments], indent=2, ensure_ascii=False),
        encoding="utf-8")

    (out / "edit_plan.review.md").write_text(
        _render_review_md(plan, self_review, clips_by_index, kind="self"), encoding="utf-8")
    if independent_review is not None:
        (out / "edit_plan.independent-review.md").write_text(
            _render_review_md(plan, independent_review, clips_by_index, kind="independent"),
            encoding="utf-8")

    if audit is not None:
        (out / "assembly_audit.json").write_text(
            json.dumps(asdict(audit), indent=2, ensure_ascii=False), encoding="utf-8")

    (out / "upstream_notes.md").write_text(
        generate_upstream_notes(plan, clips_by_index, audit), encoding="utf-8")

    return out


# --------------------------------------------------------------------------
# Upstream feedback — "design for the cut"
# --------------------------------------------------------------------------
def generate_upstream_notes(
    plan: EditPlan, clips_by_index: dict[int, ClipAsset], audit: AssemblyAudit | None
) -> str:
    lines = [
        "# Upstream notes — design the scenes/clips FOR the cut",
        "",
        "Auto-generated by the assembly stage. Feeds the scene-plan + clip-prompt",
        "stages so the next episode's clips drop into the cut with less fighting.",
        "",
        "## What was hard to fit this run",
        "",
    ]
    hard: list[str] = []
    for s in plan.body_slots:
        clip = clips_by_index.get(s.scene_index)
        if clip is None:
            continue
        natural = clip.natural_duration_s or 1.0
        trim_loss = max(0.0, (natural - s.source_span_s) / natural)
        if s.op == "speed+trim" and trim_loss > 0.35:
            hard.append(
                f"- **#{s.scene_index:02d} {clip.title}** — slot {s.slot_duration_s:.1f}s, "
                f"played {s.speed_factor:.2f}x AND trimmed {trim_loss*100:.0f}% "
                f"(role={clip.viral_role}). Design as a HELD tableau with one dominant "
                "motion so it survives ~2x and reads in ~2-3s."
            )
        elif s.speed_factor >= 2.0:
            hard.append(
                f"- **#{s.scene_index:02d} {clip.title}** — needed {s.speed_factor:.2f}x. "
                "Slow the Kling motion / front-load the payload so the speed-up looks intentional."
            )
    lines += hard or ["- (nothing fought the cut — clips fit cleanly.)"]

    # single-clip section pressure
    section_counts: dict[str, int] = {}
    for s in plan.body_slots:
        section_counts[s.section] = section_counts.get(s.section, 0) + 1
    tight = [s for s in plan.body_slots if s.slot_duration_s < 2.5 and section_counts.get(s.section, 0) == 1]
    if tight:
        lines += [
            "",
            "## Short single-clip windows that want a dedicated insert",
            "",
        ]
        for s in tight:
            clip = clips_by_index.get(s.scene_index)
            t = clip.title if clip else "?"
            lines.append(
                f"- Section **{s.section}** is only {s.slot_duration_s:.1f}s and holds one "
                f"clip (#{s.scene_index:02d} {t}). Plan a purpose-built ~2s INSERT scene "
                "(a single macro detail) for this beat instead of squeezing a 10s clip."
            )

    if audit and audit.reroll_scene_indices:
        lines += [
            "",
            "## Vision-flagged clip/word mismatches (re-plan or re-roll)",
            "",
        ]
        for v in audit.slots:
            if not v.passed:
                lines.append(f"- #{v.scene_index:02d} under \"{v.words}\" — {v.note}")

    lines += [
        "",
        "## Standing 'design for the cut' rules",
        "",
        "- Hero scene = the one most on-thread image (here the kiss); it bookends "
        "start+end, so render it with a clean, iconic, near-still composition.",
        "- Every clip will likely be sped 1.2-2.2x: favour ONE dominant motion, avoid "
        "busy multi-action that turns to mush when accelerated.",
        "- Tiny narration beats (a one-line aside, a single quoted phrase) deserve a "
        "purpose-built ~2s macro insert, not a full 10s scene.",
        "- Front-load the emotional payload (the tear, the embrace) in the first half "
        "of the clip so head-biased trims keep it.",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Review markdown
# --------------------------------------------------------------------------
def _render_review_md(plan, review, clips_by_index, kind: str) -> str:
    label = "Independent red-team audit" if kind == "independent" else "Self-review panel"
    lines = [
        f"# Edit plan — {label}",
        "",
        f"**Verdict:** `{review.overall}`  ·  **Failed gates:** {len(review.failed_gates)}",
        "",
        "## How the clips map to the words",
        plan.narration_reading or "_(not provided)_",
        "",
        "## Slots",
    ]
    for s in plan.slots:
        clip = clips_by_index.get(s.scene_index)
        t = clip.title if clip else "?"
        lines.append(
            f"- `{s.order:>2}` **{s.role}/{s.section}** — #{s.scene_index:02d} {t} · "
            f"{s.slot_start_s:.2f}-{s.slot_end_s:.2f}s ({s.slot_duration_s:.2f}s) · "
            f"{s.speed_factor:.2f}x · {s.op}"
            + (f"  \n  _{s.rationale}_" if s.rationale else "")
        )
    lines += ["", f"## {label.split(' ')[0]} panel"]
    for a in review.panel:
        lines.append(f"- **{a.agent}** — `{a.verdict}` — {a.note}")
    lines += ["", "## Gates"]
    for g in review.gates:
        line = f"- **{g.gate}** — `{g.verdict}` — {g.evidence}"
        if g.verdict.upper().strip() != "PASS" and g.fix:
            line += f"  \n  _fix:_ {g.fix}"
        lines.append(line)
    if review.priority_fixes:
        lines += ["", "## Priority fixes"]
        lines += [f"{i}. {f}" for i, f in enumerate(review.priority_fixes, 1)]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Browser index.html — the timeline jigsaw
# --------------------------------------------------------------------------
def write_index_html(
    v1_folder: Path,
    plan: EditPlan,
    clips: list[ClipAsset],
    segments: list[NarrationSegment],
    provider: str,
    audit: AssemblyAudit | None = None,
) -> Path:
    out = assembly_dir(v1_folder)
    out.mkdir(parents=True, exist_ok=True)
    clips_by_index = {c.scene_index: c for c in clips}
    audit_by_order = {v.order: v for v in (audit.slots if audit else [])}

    body = plan.body_slots
    avg_speed = sum(s.speed_factor for s in body) / len(body) if body else 0.0

    cut_rel = VIRAL_CUT_NAME
    reel_rel = REEL_NAME
    reel_exists = (out / REEL_NAME).exists()

    # per-slot cards (timeline order)
    cards = []
    for s in plan.slots:
        clip = clips_by_index.get(s.scene_index)
        png_rel = f"../visual/{provider}/{clip.slug and f'{s.scene_index:02d}_{clip.slug}'}.png" if clip else ""
        words = _section_words(segments, s.section)
        v = audit_by_order.get(s.order)
        verdict_html = ""
        if v is not None:
            cls = "pass" if v.passed else "fail"
            verdict_html = f'<span class="verdict {cls}">verify {"PASS" if v.passed else "FAIL"}</span> {_h(v.note)}'
        cards.append(
            '<div class="slot">'
            f'<div class="thumb"><img src="{_h(png_rel)}" alt="#{s.scene_index}"></div>'
            '<div class="slotmeta">'
            f'<span class="ord">{s.order:02d}</span>'
            f'<span class="role {s.role}">{_h(s.role)}</span>'
            f'<span class="sec">{_h(s.section)}</span>'
            f'<span class="ref">#{s.scene_index:02d}</span>'
            f'<span class="ttl">{_h(clip.title if clip else "?")}</span>'
            f'<div class="nums">{s.slot_start_s:.2f}–{s.slot_end_s:.2f}s · '
            f'{s.slot_duration_s:.2f}s · <b>{s.speed_factor:.2f}×</b> · {_h(s.op)}</div>'
            f'<div class="words">“{_h(words[:140])}”</div>'
            + (f'<div class="why">{_h(s.rationale)}</div>' if s.rationale else "")
            + (f'<div class="vr">{verdict_html}</div>' if verdict_html else "")
            + '</div></div>'
        )

    title = v1_folder.parent.name + " / " + v1_folder.name
    html = _INDEX_TEMPLATE.format(
        title=_h(title),
        total=f"{plan.total_seconds:.2f}",
        nbody=len(body),
        hero=f"{plan.hero_scene_index:02d}",
        avg=f"{avg_speed:.2f}",
        cut=_h(cut_rel),
        reel_block=(f'<div class="vid"><h3>All-takes reel</h3>'
                    f'<video src="{_h(reel_rel)}" controls preload="metadata"></video></div>'
                    if reel_exists else ""),
        cards="\n".join(cards),
    )
    p = out / "index.html"
    p.write_text(html, encoding="utf-8")
    return p


def _section_words(segments: list[NarrationSegment], section: str) -> str:
    for s in segments:
        if s.section == section:
            return s.text
    return ""


def _h(s: str) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;").replace("'", "&#39;"))


_INDEX_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Assembly — {title}</title>
<style>
  :root {{ --bg:#18181b; --card:#27272a; --soft:#3f3f46; --text:#e4e4e7; --dim:#a1a1aa;
    --accent:#fde68a; --pass:#4ade80; --fail:#f87171; --border:#52525b; }}
  * {{ box-sizing:border-box; }}
  body {{ font-family:-apple-system,"Segoe UI",system-ui,sans-serif; background:var(--bg);
    color:var(--text); margin:0; padding:28px; line-height:1.4; }}
  header {{ max-width:1180px; margin:0 auto 22px; }}
  h1 {{ font-size:21px; margin:0 0 6px; }}
  .sub {{ color:var(--dim); font-size:13px; }}
  .top {{ max-width:1180px; margin:0 auto 26px; display:flex; gap:24px; flex-wrap:wrap; }}
  .vid {{ flex:1; min-width:300px; }}
  .vid h3 {{ font-size:13px; color:var(--dim); text-transform:uppercase; letter-spacing:.06em; margin:0 0 8px; }}
  video {{ width:100%; max-height:520px; background:#000; border-radius:8px; border:1px solid var(--border); }}
  .grid {{ max-width:1180px; margin:0 auto; display:flex; flex-direction:column; gap:10px; }}
  .slot {{ display:grid; grid-template-columns:120px 1fr; gap:14px; background:var(--card);
    border:1px solid var(--border); border-radius:8px; overflow:hidden; }}
  .thumb {{ background:#000; display:flex; align-items:center; }}
  .thumb img {{ width:100%; display:block; }}
  .slotmeta {{ padding:12px 16px; }}
  .ord {{ font-family:ui-monospace,monospace; color:var(--dim); margin-right:8px; }}
  .role {{ font-size:11px; padding:2px 7px; border-radius:3px; background:var(--soft);
    color:var(--text); margin-right:6px; font-family:ui-monospace,monospace; }}
  .role.hero-head, .role.hero-tail {{ background:var(--accent); color:#18181b; font-weight:700; }}
  .sec {{ font-size:11px; color:var(--dim); margin-right:8px; font-family:ui-monospace,monospace; }}
  .ref {{ font-weight:700; color:var(--accent); margin-right:8px; font-family:ui-monospace,monospace; }}
  .ttl {{ font-weight:600; }}
  .nums {{ font-size:12px; color:var(--dim); margin-top:6px; font-family:ui-monospace,monospace; }}
  .words {{ font-size:14px; margin-top:8px; color:var(--text); }}
  .why {{ font-size:12px; color:var(--dim); margin-top:6px; font-style:italic; }}
  .vr {{ font-size:12px; margin-top:8px; color:var(--dim); }}
  .verdict {{ padding:2px 7px; border-radius:3px; font-size:11px; font-weight:700; font-family:ui-monospace,monospace; }}
  .verdict.pass {{ background:rgba(74,222,128,.15); color:var(--pass); border:1px solid var(--pass); }}
  .verdict.fail {{ background:rgba(248,113,113,.15); color:var(--fail); border:1px solid var(--fail); }}
</style></head><body>
<header>
  <h1>Assembly — {title}</h1>
  <div class="sub">{nbody} body clips · hero #{hero} bookend · avg speed {avg}× · total {total}s.
    Each card shows which clip sits under which words, and how it was sped/trimmed to fit.</div>
</header>
<div class="top">
  <div class="vid"><h3>60-second viral cut</h3>
    <video src="{cut}" controls preload="metadata"></video></div>
  {reel_block}
</div>
<div class="grid">
{cards}
</div>
</body></html>
"""
