$url1 = higgsfield generate create nano_banana_pro --prompt "One single storyboard page of hand-drawn animation development art, delicate ink linework and watercolor on aged cream paper, laid out like a real found piece of production art. Top-left title, handwrite: `"SEQ: THE CROSS`". Top-right frame number, handwrite: `"F01`". Across the top, a row of exactly three small labeled storyboard panels numbered 1, 2, 3: panel 1 a small sketch of his mother Mary standing at the foot of the cross, one hand pressed to her mouth, grief held with quiet dignity, panel 2 a small sketch of Roman soldiers below the cross, one crouched casting lots on the ground for his garment, spear and helmet loosely inked, panel 3 a small establishing sketch of Golgotha, the bare skull-shaped hill outside the city wall, three crosses in silhouette against a darkening sky. Below them, ONE large full-scene illustration filling the lower half of the page — a HELD SINGLE, close on Jesus alone: Jesus alone on the cross at Golgotha, his upper body filling the frame, arms outstretched along the crossbeam, head bowed slightly; the sky behind him gone dark though it is midday, the bare hill falling away soft and unfinished at the page edges beneath him; stillness and complete surrender. Jesus (match the attached reference for his face, hair, and build): a first-century Jewish man in his early thirties, weathered calm face, dark textured shoulder-length hair, short natural beard, drawn in broad confident economical ink strokes; here on the cross, stripped for the crucifixion but modestly wrapped in a plain loincloth, a crown of twisted thorns pressed into his brow, faint ink marks of the nails at his hands, a faint incomplete calligraphic halo of muted gold-and-blue curls, never a solid disc. Stage 3 dosage: the blue-and-gold ink motif is fully diffused but subdued — quiet threads of blue with the barest trace of gold woven faintly through the darkened sky and along the base of the cross, not tied to any single figure, behaving like wet ink bled deep into the paper, grave and quiet, never bright, never celebratory. Small handwritten production notes integrated naturally on the page: a caption beneath the main scene, handwrite: `"Father, forgive them`", and a corner note, handwrite: `"NOTE: darkness at noon`". Palette: black ink, ochre, muted brown, olive green, clay-red, touches of soft gold wash on aged cream paper with visible grain. Not photorealistic, not anime, not Disney, no polished graphic design, no clean comic-book inking, no Renaissance religious staging, no glowing spiritual VFX — every blue or gold element behaves like literal wet ink bleeding into paper, never a magic-particle glow." --image "F:\slk\PycharmProjects\JesusInTheBible\.claude\skills\swirls-of-life\references\jesus_ref.png" --aspect_ratio 9:16 --resolution 2k --wait

Write-Host "URL 1: $url1"

if ($url1 -match "http[s]?://.*") {
    $matched_url = $matches[0]
    Invoke-WebRequest -Uri $matched_url -OutFile "F:\slk\PycharmProjects\JesusInTheBible\poc_living_water_ink_style_test\test_the_cross\the_cross_9x16_antigravity.png"
    Write-Host "Saved to F:\slk\PycharmProjects\JesusInTheBible\poc_living_water_ink_style_test\test_the_cross\the_cross_9x16_antigravity.png"
}

$url2 = higgsfield generate create nano_banana_pro --prompt "One single storyboard page of hand-drawn animation development art, delicate ink linework and watercolor on aged cream paper, laid out like a real found piece of production art. Top-left title, handwrite: `"SEQ: THE CROSS`". Top-right frame number, handwrite: `"F01`". Across the top, a row of exactly three small labeled storyboard panels numbered 1, 2, 3: panel 1 a small sketch of his mother Mary standing at the foot of the cross, one hand pressed to her mouth, grief held with quiet dignity, panel 2 a small sketch of Roman soldiers below the cross, one crouched casting lots on the ground for his garment, spear and helmet loosely inked, panel 3 a small establishing sketch of Golgotha, the bare skull-shaped hill outside the city wall, three crosses in silhouette against a darkening sky. Below them, ONE large full-scene illustration filling the lower half of the page — a HELD SINGLE, close on Jesus alone: Jesus alone on the cross at Golgotha, his upper body filling the frame, arms outstretched along the crossbeam, head bowed slightly; the sky behind him gone dark though it is midday, the bare hill falling away soft and unfinished at the page edges beneath him; stillness and complete surrender. Jesus (match the attached reference for his face, hair, and build): a first-century Jewish man in his early thirties, weathered calm face, dark textured shoulder-length hair, short natural beard, drawn in broad confident economical ink strokes; here on the cross, stripped for the crucifixion but modestly wrapped in a plain loincloth, a crown of twisted thorns pressed into his brow, faint ink marks of the nails at his hands, a faint incomplete calligraphic halo of muted gold-and-blue curls, never a solid disc. Stage 3 dosage: the blue-and-gold ink motif is fully diffused but subdued — quiet threads of blue with the barest trace of gold woven faintly through the darkened sky and along the base of the cross, not tied to any single figure, behaving like wet ink bled deep into the paper, grave and quiet, never bright, never celebratory. Small handwritten production notes integrated naturally on the page: a caption beneath the main scene, handwrite: `"Father, forgive them`", and a corner note, handwrite: `"NOTE: darkness at noon`". Palette: black ink, ochre, muted brown, olive green, clay-red, touches of soft gold wash on aged cream paper with visible grain. Not photorealistic, not anime, not Disney, no polished graphic design, no clean comic-book inking, no Renaissance religious staging, no glowing spiritual VFX — every blue or gold element behaves like literal wet ink bleeding into paper, never a magic-particle glow." --image "F:\slk\PycharmProjects\JesusInTheBible\.claude\skills\swirls-of-life\references\jesus_ref.png" --aspect_ratio 16:9 --resolution 2k --wait

Write-Host "URL 2: $url2"

if ($url2 -match "http[s]?://.*") {
    $matched_url = $matches[0]
    Invoke-WebRequest -Uri $matched_url -OutFile "F:\slk\PycharmProjects\JesusInTheBible\poc_living_water_ink_style_test\test_the_cross\the_cross_16x9_antigravity.png"
    Write-Host "Saved to F:\slk\PycharmProjects\JesusInTheBible\poc_living_water_ink_style_test\test_the_cross\the_cross_16x9_antigravity.png"
}
